{ pkgs, ... }:

let
  gcloud = pkgs.google-cloud-sdk.withExtraComponents [ pkgs.google-cloud-sdk.components.gke-gcloud-auth-plugin ];
in

{

  environment = {
    systemPackages = with pkgs; [
      tree
      eza
      tmux
      unzip
      gnupg
      unrar
      btop
      binutils
      htop
      zoxide
       geekbench
       veracrypt
       borgbackup
       kernelshark
       xdg-utils
      glib
      powerline-fonts
      roboto
      font-awesome
      noto-fonts-emoji-blob-bin
      desktop-file-utils
      pciutils
       inetutils
       lshw
       usbutils
       vdpauinfo
       lm_sensors
       ncdu
       hping
       fastfetch
       acpi
       nmap
      p0f
      tcpdump
      wireshark
      rustscan
      pritunl-client
       openfortivpn
       git 
      cachix 
      flat-remix-gnome
    flat-remix-icon-theme
    gnomeExtensions.pop-shell
    gnomeExtensions.easyeffects-preset-selector
    gnomeExtensions.appindicator
    pavucontrol
      easyeffects
      qpwgraph
      ffmpeg_7-full
      gst_all_1.gstreamer
      gst_all_1.gst-vaapi
      gst_all_1.gst-plugins-ugly
      gst_all_1.gst-plugins-good
      gst_all_1.gst-plugins-bad
      gst_all_1.gst-libav
      gimp
      inkscape
      obs-studio
      mpv
      spotify
      vlc
      stremio
      heroic
      libreoffice
      telegram-desktop
      slack
      discord
            google-chrome
      brave
      firefox
      copyq
      transmission_4-gtk
      appimage-run
      distrobox
      pre-commit
        devenv
        argo
        jq
        stripe-cli
        openssl
        postman
        helix
        vim
        jetbrains.pycharm-professional
        jetbrains.webstorm
        nix-search-cli
        jetbrains.datagrip
        dbeaver-bin
        gh
        typora
        asciinema
        kubectl
        lens
        gcloud
        istioctl
        kubernetes-helm
        minikube
        terraform
        terragrunt
        awscli2
        remmina
        azure-cli
        azure-cli-extensions.azure-devops
        alacritty
        figma-linux
        gnome-notes
        endeavour
        _1password-gui
        pinentry-curses
        code-cursor
        vscode-fhs
        kitty
    ];
  };

  fonts = {
    packages = with pkgs; [
           nerd-fonts._0xproto
           nerd-fonts.droid-sans-mono
           nerd-fonts.ubuntu-sans
           nerd-fonts.ubuntu
           nerd-fonts.jetbrains-mono
         ];
  };
}
