name: Testing flakes

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  flake-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Check flake
        run: nix flake check --verbose
